### ISSUE TITLE
GNOME[3.12]-like tabs

### ISSUE THREAD

**Issue by bandali** [gnome-integration-team/chrome-gnome#5]
Would it be possible to do a redesign to make tabs look like the new GNOME 3.12 tabs? I don't really know much about extensions and I'm not a designer or I'd have done it myself..

**Comment by garrett** [comment]
Unless something has changed recently, it's impossible. Chrome doesn't allow it. Sorry.

**Comment by bandali** [comment]
Oh OK :) So, we can't change the "general" shape and curves of tabs in chrome, right?

Anyways,
Thanks :)

**Comment by garrett** [comment]
No, it's not possible. I wish it were.

Meanwhile, if you happen to be up for switching browsers, we're implementing the new GNOME 3.12 style tabs for Firefox: https://github.com/gnome-integration-team/firefox-gnome/issues/235 … and there's always Epiphany (aka: "Web") too
